### ISSUE TITLE
Error con cypress

### ISSUE THREAD

**Issue by OscarSala96** [OscarSala96/practica_dwec_gestor_presupuesto#1]
Hola @pedroprieto , me sale este error cuando intento hacer el test 4:
 TypeError: The following error originated from your application code, not from Cypress.     

  > Cannot add property valor, object is not extensible

He intentado solucionarlo pero no doy con la tecla.

**Comment by pedroprieto** [comment]
Buenas,

No tienes subido el código, por lo que no puedo verlo. Pero ese error suele aparecer cuando se te ha olvidado utilizar el operador `new` al crear un nuevo objeto. Seguramente hayas puesto algo como `gasto = CrearGasto()` en lugar de `gasto = new CrearGasto()`.

Un saludo!!

**Comment by OscarSala96** [comment]
Era eso, muchas gracias!
